<a href="https://colab.research.google.com/github/roy392/cautious-goggles/blob/main/Tugas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as roy

In [24]:

a = roy.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])

print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [8]:
a[:]
print('baris ke-2 = ', a[1])
print('entry ke-2 & 3 baris ke-2 = ', a[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', a[:2, 1])

baris ke-2 =  [2 4 1]
entry ke-2 & 3 baris ke-2 =  [4 1]
entry pertama & 2 kolom ke-2 =  [3 4]


In [9]:
a[2]
print('baris ke-2 = ', a[1])
print('entry ke-2 & 3 baris ke-2 = ', a[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', a[:2, 1])

baris ke-2 =  [2 4 1]
entry ke-2 & 3 baris ke-2 =  [4 1]
entry pertama & 2 kolom ke-2 =  [3 4]


In [10]:
a[1:]
print('baris ke-2 = ', a[1])
print('entry ke-2 & 3 baris ke-2 = ', a[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', a[:2, 1])

baris ke-2 =  [2 4 1]
entry ke-2 & 3 baris ke-2 =  [4 1]
entry pertama & 2 kolom ke-2 =  [3 4]


In [25]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [[2 4 1]
 [3 6 7]]
a[:3] =  [[1 3 0]
 [2 4 1]
 [3 6 7]]


In [15]:
import numpy as roy
A = roy.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [3 6 7]
entry ke-1 & 2 baris ke-3 =  [3 6]
entry ke-2 & 3 kolom ke-3 =  [1 7]


In [16]:
A[:]
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [3 6 7]
entry ke-1 & 2 baris ke-3 =  [3 6]
entry ke-2 & 3 kolom ke-3 =  [1 7]


In [17]:
A[2]
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [3 6 7]
entry ke-1 & 2 baris ke-3 =  [3 6]
entry ke-2 & 3 kolom ke-3 =  [1 7]


In [18]:
a[1:]
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [3 6 7]
entry ke-1 & 2 baris ke-3 =  [3 6]
entry ke-2 & 3 kolom ke-3 =  [1 7]


In [19]:
import numpy as roy
C = roy.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])
C = A*A

print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])
print('perkalian antar entry = ')
print(C)

baris ke-3 =  [3 6 7]
entry ke-1 & 2 baris ke-3 =  [3 6]
entry ke-2 & 3 kolom ke-3 =  [1 7]
perkalian antar entry = 
[[ 1  9  0]
 [ 4 16  1]
 [ 9 36 49]]


In [26]:
import numpy as roy

In [27]:
A = roy.array([[1, 2], [7,8]])
B = roy.array([[3, 5], [1,6]])

In [29]:
A = roy.array([[1, 2], [7,8]])
print("Hasil dari 2*A : ", 2*A)
print("Hasil dari 2+A : ", 2+A)
print("Hasil dari A+B : ", A+B)
print("Hasil dari Determinan A : ", roy.linalg.det(A))

Hasil dari 2*A :  [[ 2  4]
 [14 16]]
Hasil dari 2+A :  [[ 3  4]
 [ 9 10]]
Hasil dari A+B :  [[ 4  7]
 [ 8 14]]
Hasil dari Determinan A :  -6.0


In [30]:
B = roy.array([[3, 5], [1,6]])
print("Hasil dari 2*A : ", 2*A)
print("Hasil dari 2+A : ", 2+A)
print("Hasil dari A+B : ", A+B)
print("Hasil dari Determinan A : ", roy.linalg.det(A))

Hasil dari 2*A :  [[ 2  4]
 [14 16]]
Hasil dari 2+A :  [[ 3  4]
 [ 9 10]]
Hasil dari A+B :  [[ 4  7]
 [ 8 14]]
Hasil dari Determinan A :  -6.0


In [31]:
A = roy.array([[1, 2], [7,8]])
B = roy.array([[3, 5], [1,6]])
print("Hasil dari 2*A : ", 2*A)
print("Hasil dari 2+A : ", 2+A)
print("Hasil dari A+B : ", A+B)
print("Hasil dari Determinan A : ", roy.linalg.det(A))
print("Hasil dari Determinan A : ", roy.linalg.det(B))

Hasil dari 2*A :  [[ 2  4]
 [14 16]]
Hasil dari 2+A :  [[ 3  4]
 [ 9 10]]
Hasil dari A+B :  [[ 4  7]
 [ 8 14]]
Hasil dari Determinan A :  -6.0
Hasil dari Determinan A :  13.000000000000005
